### ISSUE TITLE
data files missing for new users

### ISSUE THREAD

**Issue by annapapitto** [marwahaha/friendlog#51]
data/friends.json and data/events.json are missing for new users and things error out:

```
anna@Naboo: ~/friendlog $ friends add Fake 8
fs.js:667
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '/Users/anna/friendlog/data/friends.json'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at loadFriendsData (/Users/anna/friendlog/index.js:22:23)
    at addFriend (/Users/anna/friendlog/index.js:95:17)
    at main (/Users/anna/friendlog/index.js:226:5)
    at Object.<anonymous> (/Users/anna/friendlog/index.js:244:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
```

Some ideas:
1. put creating these into the Setup portion of the Readme
2. make an install script that creates them
3. maybe there's a way to use node to make them when starting up, if they don't exist? idk, i've not really used node

**Comment by prendradjaja** [comment]
Wait, you [already created this..?](https://github.com/marwahaha/friendlog/issues/51)
